import type { NewsItem } from "./types";

// Timestamps are generated relative to page load so the tape always looks
// live: "minutesAgo" offsets are converted to ISO strings when the module
// is first evaluated. The clusters simulate a trading day — an overnight
// session (roughly 5–16h ago), a pre-market block, and a live intraday tape.

const NOW = Date.now();

const ts = (minutesAgo: number) =>
  new Date(NOW - minutesAgo * 60_000).toISOString();

type Seed = Omit<NewsItem, "id" | "timestamp"> & { minutesAgo: number };

const seeds: Seed[] = [
  // ───────────────────────── intraday tape (0–2h) ─────────────────────────
  {
    minutesAgo: 2,
    headline: "FED'S WALLER: SEES CASE FOR CONTINUED PATIENCE ON RATE CUTS",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["SPY", "QQQ", "TLT"],
    assetClasses: ["equities", "options", "futures", "forex"],
    pairs: ["EUR/USD", "USD/JPY"],
    eventType: "fed-speak",
    body: "Federal Reserve Governor Christopher Waller said the central bank can afford to be patient on further rate cuts, citing resilient labor data and inflation that remains above target. He added that the bar for a move at the next meeting is 'higher than markets appear to be pricing.'",
    marketReaction: [
      { instrument: "ES", move: "-0.4%" },
      { instrument: "10Y", move: "+5bp" },
      { instrument: "DXY", move: "+0.3%" },
    ],
  },
  {
    minutesAgo: 4,
    headline: "NVDA EXTENDS LOSSES, DOWN 3.2% ON DAY AS CHIP SECTOR SLIDES",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["NVDA", "SMH", "AMD"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Nvidia shares extended declines in afternoon trading, dragging the Philadelphia Semiconductor Index lower. Traders cited profit-taking after a strong run and caution ahead of export-license headlines out of Washington.",
    marketReaction: [
      { instrument: "NVDA", move: "-3.2%" },
      { instrument: "SMH", move: "-2.1%" },
    ],
  },
  {
    minutesAgo: 7,
    headline: "Treasury yields push higher after Waller remarks; 2-year at session peak",
    source: "CNBC",
    sourceType: "outlet",
    impact: "low",
    tickers: ["TLT", "SPY"],
    assetClasses: ["equities", "futures"],
    eventType: "other",
    body: "Short-end yields rose to session highs as traders trimmed rate-cut bets following Governor Waller's comments. Fed funds futures now price roughly 40bp of easing by year-end, down from 48bp this morning.",
  },
  {
    minutesAgo: 9,
    headline: "@DeItaone: *TSLA RECALLS 1.1M VEHICLES IN CHINA OVER STEERING SOFTWARE — REGULATOR",
    source: "@DeItaone",
    sourceType: "social",
    impact: "high",
    tickers: ["TSLA"],
    assetClasses: ["equities", "options"],
    eventType: "tweet",
    body: "Chinese market regulator SAMR posted a filing showing Tesla will recall approximately 1.1 million vehicles in China to fix a steering-assist software issue via OTA update. Tesla shares dropped on the headline before paring losses as traders noted the fix is software-only.",
    marketReaction: [
      { instrument: "TSLA", move: "-2.6%" },
    ],
  },
  {
    minutesAgo: 12,
    headline: "EIA: CRUDE INVENTORIES -2.8M BBL VS -1.2M EXPECTED",
    source: "EIA",
    sourceType: "econ-calendar",
    impact: "medium",
    tickers: ["USO", "XLE", "XOM"],
    assetClasses: ["futures", "equities"],
    eventType: "econ-release",
    body: "US crude stockpiles fell 2.8 million barrels last week, a larger draw than the 1.2 million consensus. Gasoline inventories were roughly flat. WTI added to gains after the print.",
    marketReaction: [
      { instrument: "CL", move: "+1.1%" },
    ],
  },
  {
    minutesAgo: 15,
    headline: "Apple supplier Foxconn said to weigh additional US server capacity, sources say",
    source: "Bloomberg",
    sourceType: "outlet",
    impact: "low",
    tickers: ["AAPL"],
    assetClasses: ["equities"],
    eventType: "company-news",
    body: "Foxconn is evaluating an expansion of its US server assembly footprint to serve AI data-center demand, according to people familiar with the matter. No final decision has been made.",
  },
  {
    minutesAgo: 18,
    headline: "META UNVEILS NEW AD-RANKING MODEL; SAYS EARLY TESTS SHOW 4% CONVERSION LIFT",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["META"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Meta introduced a new ads ranking architecture it says lifts conversions roughly 4% in early tests across Reels placements. Analysts flagged the update as supportive of second-half revenue estimates.",
    marketReaction: [
      { instrument: "META", move: "+1.4%" },
    ],
  },
  {
    minutesAgo: 22,
    headline: "USD/JPY prints fresh session high as US yields climb",
    source: "ForexLive",
    sourceType: "outlet",
    impact: "low",
    tickers: [],
    assetClasses: ["forex", "futures"],
    pairs: ["USD/JPY"],
    eventType: "other",
    body: "Dollar-yen tracked the move in front-end Treasury yields to a fresh session high. Traders remain wary of jawboning from Japanese officials near recent intervention zones.",
  },
  {
    minutesAgo: 25,
    headline: "GOLDMAN RAISES S&P 500 YEAR-END TARGET, CITES EARNINGS BREADTH",
    source: "Reuters",
    sourceType: "wire",
    impact: "low",
    tickers: ["SPY"],
    assetClasses: ["equities"],
    eventType: "analyst",
    body: "Goldman Sachs strategists lifted their S&P 500 year-end target, pointing to broadening earnings growth beyond mega-cap tech and resilient margins.",
  },
  {
    minutesAgo: 28,
    headline: "AMD: DATA CENTER GPU SHIPMENTS 'TRACKING AHEAD OF PLAN' — CFO AT CONFERENCE",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["AMD", "NVDA"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Speaking at an industry conference, AMD's CFO said MI-series accelerator shipments are tracking ahead of internal plan for the quarter and reiterated the full-year data center outlook.",
    marketReaction: [
      { instrument: "AMD", move: "+2.3%" },
    ],
  },
  {
    minutesAgo: 33,
    headline: "White House trade adviser: chip export review 'weeks, not months' from conclusion",
    source: "CNBC",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["NVDA", "AMD", "SMH"],
    assetClasses: ["equities", "options"],
    eventType: "geopolitical",
    body: "A senior administration official told CNBC the review of advanced chip export licenses is 'weeks, not months' from conclusion, and that decisions would balance security concerns with commercial interests.",
  },
  {
    minutesAgo: 38,
    headline: "@unusual_whales: Massive 0DTE put volume hitting SPX 30 minutes into the session, largest sweep $4.1M premium",
    source: "@unusual_whales",
    sourceType: "social",
    impact: "low",
    tickers: ["SPY", "SPX"],
    assetClasses: ["options"],
    eventType: "tweet",
    body: "Options flow account flags outsized same-day-expiry put sweeps on SPX shortly after the open. Flow-watchers note 0DTE activity has been a fixture around macro headlines all week.",
  },
  {
    minutesAgo: 44,
    headline: "BOEING WINS 60-JET WIDE-BODY ORDER FROM GULF CARRIER — STATEMENT",
    source: "Reuters",
    sourceType: "wire",
    impact: "low",
    tickers: ["BA"],
    assetClasses: ["equities"],
    eventType: "company-news",
    body: "Boeing announced a firm order for 60 wide-body aircraft from a Gulf carrier, with options for 20 more. Deliveries are slated to begin in 2028.",
  },
  {
    minutesAgo: 51,
    headline: "MSFT: AZURE CAPACITY CONSTRAINTS 'LARGELY RESOLVED' BY Q4 — EXEC",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["MSFT"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "A Microsoft executive said Azure AI capacity constraints should be largely resolved by the fiscal fourth quarter as new data centers come online, easing a concern analysts have flagged for two quarters.",
    marketReaction: [
      { instrument: "MSFT", move: "+0.9%" },
    ],
  },
  {
    minutesAgo: 58,
    headline: "Bitcoin reclaims $100K handle as ETF inflows resume",
    source: "CoinDesk",
    sourceType: "outlet",
    impact: "low",
    tickers: ["BTC", "COIN", "IBIT"],
    assetClasses: ["crypto", "equities"],
    eventType: "other",
    body: "Bitcoin traded back above $100,000 as spot ETF products logged their first net inflows in four sessions. Funding rates remain modest, suggesting the move is not leverage-driven.",
  },
  {
    minutesAgo: 65,
    headline: "ECB'S LAGARDE: DISINFLATION ON TRACK, POLICY DECISIONS MEETING-BY-MEETING",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: [],
    assetClasses: ["forex", "futures"],
    pairs: ["EUR/USD"],
    eventType: "fed-speak",
    body: "ECB President Christine Lagarde reiterated that euro-area disinflation remains on track and the Governing Council will decide meeting by meeting. She declined to commit to a timeline for further cuts.",
    marketReaction: [
      { instrument: "EUR/USD", move: "-0.2%" },
    ],
  },
  {
    minutesAgo: 72,
    headline: "Regional banks rally after Fed's Bowman floats lighter capital rules for mid-size lenders",
    source: "CNBC",
    sourceType: "outlet",
    impact: "low",
    tickers: ["KRE", "JPM"],
    assetClasses: ["equities"],
    eventType: "fed-speak",
    body: "Shares of regional lenders gained after Fed Vice Chair for Supervision Michelle Bowman suggested capital requirements for mid-size banks could be recalibrated in a coming proposal.",
  },
  {
    minutesAgo: 80,
    headline: "NFLX ANNOUNCES PRICE INCREASE ON STANDARD AND PREMIUM PLANS IN US, UK",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["NFLX"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Netflix raised prices on its standard and premium tiers in the US and UK, its first increase in over a year. The ad-supported tier is unchanged. Street models imply roughly 3% incremental revenue on the move.",
    marketReaction: [
      { instrument: "NFLX", move: "+2.8%" },
    ],
  },
  {
    minutesAgo: 90,
    headline: "US 10-YEAR AUCTION TAILS 1.2BP; BID-TO-COVER 2.42 VS 2.55 PRIOR",
    source: "US Treasury",
    sourceType: "econ-calendar",
    impact: "medium",
    tickers: ["TLT"],
    assetClasses: ["futures", "equities"],
    eventType: "econ-release",
    body: "The $42 billion 10-year note auction tailed by 1.2 basis points with softer-than-average demand metrics. Dealers were left with an above-average share, pressuring the long end after the results.",
    marketReaction: [
      { instrument: "10Y", move: "+3bp" },
      { instrument: "ZN", move: "-0.2%" },
    ],
  },
  {
    minutesAgo: 100,
    headline: "Barclays upgrades Palantir to overweight, lifts target on government AI bookings",
    source: "Barclays",
    sourceType: "outlet",
    impact: "low",
    tickers: ["PLTR"],
    assetClasses: ["equities"],
    eventType: "analyst",
    body: "Barclays upgraded Palantir to overweight, citing acceleration in US government AI contract bookings and improving commercial net revenue retention.",
  },
  {
    minutesAgo: 110,
    headline: "GOOGL: DOJ REMEDIES HEARING SET FOR NEXT MONTH; JUDGE SIGNALS NARROW SCOPE",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["GOOGL"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "The judge overseeing the DOJ search-remedies case scheduled next month's hearing and signaled the court favors behavioral remedies over structural separation, according to courtroom reports.",
    marketReaction: [
      { instrument: "GOOGL", move: "+1.1%" },
    ],
  },
  {
    minutesAgo: 125,
    headline: "Copper hits four-month high on Chilean supply disruption",
    source: "Bloomberg",
    sourceType: "outlet",
    impact: "low",
    tickers: ["FCX"],
    assetClasses: ["futures", "equities"],
    eventType: "other",
    body: "Copper futures touched a four-month high after a labor stoppage at a major Chilean mine entered its second week. Analysts see limited near-term substitution capacity.",
  },

  // ──────────────────────── pre-market block (2–5h) ────────────────────────
  {
    minutesAgo: 145,
    headline: "US CPI M/M +0.2% VS +0.3% EXPECTED; Y/Y 2.4% VS 2.5% EXP, PRIOR 2.6%",
    source: "BLS",
    sourceType: "econ-calendar",
    impact: "high",
    tickers: ["SPY", "QQQ", "TLT", "GLD"],
    assetClasses: ["equities", "options", "futures", "forex"],
    pairs: ["EUR/USD", "USD/JPY"],
    eventType: "econ-release",
    body: "Headline CPI rose 0.2% on the month against 0.3% expected, bringing the annual rate to 2.4%. Core came in at 0.2% m/m, also a tenth below consensus. Shelter inflation decelerated to its slowest pace since 2021. Rate-cut odds for the next FOMC meeting jumped on the release.",
    marketReaction: [
      { instrument: "ES", move: "+0.9%" },
      { instrument: "NQ", move: "+1.3%" },
      { instrument: "10Y", move: "-7bp" },
      { instrument: "DXY", move: "-0.5%" },
    ],
  },
  {
    minutesAgo: 150,
    headline: "GOLD SPIKES TO RECORD HIGH ABOVE $3,150 AFTER SOFT CPI PRINT",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["GLD", "GDX"],
    assetClasses: ["futures", "equities"],
    eventType: "other",
    body: "Spot gold jumped to a record above $3,150/oz as Treasury yields and the dollar fell on the cooler-than-expected inflation report.",
    marketReaction: [
      { instrument: "GC", move: "+1.2%" },
    ],
  },
  {
    minutesAgo: 160,
    headline: "INITIAL JOBLESS CLAIMS 219K VS 225K EXPECTED, PRIOR REVISED TO 222K",
    source: "DOL",
    sourceType: "econ-calendar",
    impact: "medium",
    tickers: ["SPY"],
    assetClasses: ["equities", "futures"],
    eventType: "econ-release",
    body: "First-time unemployment claims came in at 219,000, below the 225,000 consensus. Continuing claims edged up to 1.87 million, in line with expectations.",
    marketReaction: [
      { instrument: "ES", move: "+0.1%" },
    ],
  },
  {
    minutesAgo: 175,
    headline: "JPM BEATS: Q2 EPS $4.87 VS $4.61 EST; NII GUIDANCE RAISED FOR FULL YEAR",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["JPM", "XLF"],
    assetClasses: ["equities", "options"],
    eventType: "earnings",
    body: "JPMorgan reported second-quarter EPS of $4.87 versus $4.61 expected, on revenue of $45.9 billion. The bank raised full-year net interest income guidance by roughly $1 billion and flagged 'healthy but normalizing' consumer credit. Trading revenue rose 12% year over year.",
    marketReaction: [
      { instrument: "JPM", move: "+3.1%" },
      { instrument: "XLF", move: "+1.0%" },
    ],
  },
  {
    minutesAgo: 190,
    headline: "Pre-market movers: NVDA, TSLA, JPM most active as futures build on CPI gains",
    source: "CNBC",
    sourceType: "outlet",
    impact: "low",
    tickers: ["NVDA", "TSLA", "JPM"],
    assetClasses: ["equities"],
    eventType: "other",
    body: "Equity futures extended gains through the pre-market with megacap tech leading. Volume leaders ahead of the open: Nvidia, Tesla and JPMorgan following its earnings beat.",
  },
  {
    minutesAgo: 205,
    headline: "UK CPI HOTTER THAN EXPECTED AT 3.1% Y/Y; CABLE JUMPS",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: [],
    assetClasses: ["forex"],
    pairs: ["GBP/USD", "EUR/GBP"],
    eventType: "econ-release",
    body: "UK inflation printed 3.1% year over year against 2.9% expected, led by services prices. Traders pared Bank of England cut expectations, lifting sterling across the board.",
    marketReaction: [
      { instrument: "GBP/USD", move: "+0.6%" },
    ],
  },
  {
    minutesAgo: 220,
    headline: "AVGO said to be in advanced talks on multi-billion custom AI chip deal with fourth hyperscaler",
    source: "The Information",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["AVGO", "NVDA"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Broadcom is in advanced negotiations to design custom AI accelerators for a fourth major cloud customer, according to a report. A deal could be announced within weeks.",
    marketReaction: [
      { instrument: "AVGO", move: "+2.4%" },
    ],
  },
  {
    minutesAgo: 240,
    headline: "Morgan Stanley cuts Apple to equal-weight on iPhone cycle timing",
    source: "Morgan Stanley",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["AAPL"],
    assetClasses: ["equities", "options"],
    eventType: "analyst",
    body: "Morgan Stanley downgraded Apple to equal-weight, arguing the next iPhone upgrade cycle is more back-half loaded than consensus assumes and that Services growth is decelerating at the margin.",
    marketReaction: [
      { instrument: "AAPL", move: "-1.8%" },
    ],
  },
  {
    minutesAgo: 260,
    headline: "German factory orders fall 2.1% m/m, third straight decline",
    source: "Destatis",
    sourceType: "econ-calendar",
    impact: "low",
    tickers: [],
    assetClasses: ["forex", "futures"],
    pairs: ["EUR/USD"],
    eventType: "econ-release",
    body: "German manufacturing orders declined 2.1% on the month, the third consecutive drop, driven by weak foreign demand for capital goods.",
  },

  // ───────────────────────── overnight session (5–16h) ─────────────────────────
  {
    minutesAgo: 320,
    headline: "TSMC JUNE-QUARTER REVENUE +38% Y/Y, BEATS GUIDANCE MIDPOINT",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["TSM", "NVDA", "AMD", "SMH"],
    assetClasses: ["equities", "options"],
    eventType: "earnings",
    body: "TSMC reported quarterly revenue up 38% year over year, ahead of its guidance midpoint, on sustained AI accelerator demand. The company said advanced-node capacity remains 'fully committed' through year-end. US-listed chip names rose in overnight trading on the print.",
    marketReaction: [
      { instrument: "TSM", move: "+3.4%" },
      { instrument: "NQ", move: "+0.4%" },
    ],
  },
  {
    minutesAgo: 350,
    headline: "BOJ'S UEDA: WILL ADJUST DEGREE OF EASING IF PRICE TARGET OUTLOOK REALIZED",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: [],
    assetClasses: ["forex", "futures"],
    pairs: ["USD/JPY", "EUR/JPY"],
    eventType: "fed-speak",
    body: "Bank of Japan Governor Kazuo Ueda told parliament the central bank will adjust the degree of monetary easing if its inflation outlook is realized, language traders read as keeping a near-term hike live. The yen firmed across the board on the remarks.",
    marketReaction: [
      { instrument: "USD/JPY", move: "-0.7%" },
      { instrument: "NKY", move: "-1.1%" },
    ],
  },
  {
    minutesAgo: 380,
    headline: "@zerohedge: Container rates Shanghai→Rotterdam +18% w/w as Red Sea diversions widen",
    source: "@zerohedge",
    sourceType: "social",
    impact: "low",
    tickers: ["ZIM", "FDX"],
    assetClasses: ["equities"],
    eventType: "tweet",
    body: "Freight-rate trackers show Asia-Europe container rates jumping 18% week over week as more carriers reroute around the Cape of Good Hope. Analysts note the inflation pass-through is modest at current levels but worth watching.",
  },
  {
    minutesAgo: 410,
    headline: "CHINA JUNE EXPORTS +7.6% Y/Y VS +5.0% EXPECTED; IMPORTS +2.1%",
    source: "Customs GA",
    sourceType: "econ-calendar",
    impact: "medium",
    tickers: ["FXI", "BABA"],
    assetClasses: ["equities", "forex", "futures"],
    pairs: ["USD/CNH", "AUD/USD"],
    eventType: "econ-release",
    body: "Chinese exports grew 7.6% year over year in June, well above the 5.0% consensus, as shippers front-loaded orders ahead of tariff deadlines. Imports rose 2.1%. The Aussie dollar, a China proxy, ticked higher on the data.",
    marketReaction: [
      { instrument: "AUD/USD", move: "+0.3%" },
    ],
  },
  {
    minutesAgo: 430,
    headline: "OPEC+ PANEL RECOMMENDS KEEPING OUTPUT POLICY UNCHANGED — DELEGATES",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["USO", "XLE"],
    assetClasses: ["futures", "equities"],
    eventType: "geopolitical",
    body: "An OPEC+ ministerial panel recommended keeping current production policy unchanged at its overnight meeting, delegates said, deferring the decision on unwinding voluntary cuts to the next full meeting.",
    marketReaction: [
      { instrument: "CL", move: "+0.5%" },
    ],
  },
  {
    minutesAgo: 455,
    headline: "SoftBank said to weigh $10B follow-on investment in OpenAI compute venture",
    source: "Bloomberg",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["NVDA", "MSFT", "ARM"],
    assetClasses: ["equities"],
    eventType: "company-news",
    body: "SoftBank is in discussions to commit up to $10 billion more to a data-center joint venture with OpenAI, people familiar said, with a decision possible this quarter. The report supported AI-infrastructure names in overnight trading.",
  },
  {
    minutesAgo: 480,
    headline: "FOMC MINUTES: 'SEVERAL' OFFICIALS SAW MERIT IN AWAITING MORE INFLATION PROGRESS",
    source: "Federal Reserve",
    sourceType: "econ-calendar",
    impact: "high",
    tickers: ["SPY", "QQQ", "TLT"],
    assetClasses: ["equities", "options", "futures", "forex"],
    pairs: ["EUR/USD"],
    eventType: "econ-release",
    body: "Minutes from the last FOMC meeting showed 'several' participants preferred to see additional months of inflation progress before easing further, while 'a couple' argued the labor market already justified a cut. Staff projections flagged tariff pass-through as an upside inflation risk into Q4.",
    marketReaction: [
      { instrument: "ES", move: "-0.3%" },
      { instrument: "2Y", move: "+4bp" },
    ],
  },
  {
    minutesAgo: 500,
    headline: "AMZN: AWS SIGNS $8B MULTI-YEAR CLOUD PACT WITH GLOBAL PHARMA GROUP",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["AMZN"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Amazon Web Services signed an $8 billion multi-year agreement to provide cloud and AI services to a global pharmaceutical group, one of AWS's largest healthcare deals to date.",
    marketReaction: [
      { instrument: "AMZN", move: "+1.2%" },
    ],
  },
  {
    minutesAgo: 520,
    headline: "Nikkei slides 1.4% as yen strengthens; exporters lead losses",
    source: "Nikkei Asia",
    sourceType: "outlet",
    impact: "low",
    tickers: ["EWJ"],
    assetClasses: ["equities", "forex"],
    pairs: ["USD/JPY"],
    eventType: "other",
    body: "Japanese equities fell as the yen firmed after Governor Ueda's parliamentary testimony, with autos and machinery exporters the biggest drags on the index.",
  },
  {
    minutesAgo: 545,
    headline: "ISRAELI STRIKES REPORTED NEAR HODEIDAH PORT; SHIPPING GROUPS REROUTE — MARITIME AGENCY",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["USO", "XLE"],
    assetClasses: ["futures", "equities"],
    eventType: "geopolitical",
    body: "A maritime security agency reported strikes near the Yemeni port of Hodeidah overnight, prompting several carriers to reroute vessels and lifting war-risk insurance premiums in the Red Sea corridor. Crude added a geopolitical premium on the headlines.",
    marketReaction: [
      { instrument: "CL", move: "+1.6%" },
      { instrument: "GC", move: "+0.4%" },
    ],
  },
  {
    minutesAgo: 570,
    headline: "COIN announces acquisition of derivatives platform for $2.9B in cash and stock",
    source: "Business Wire",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["COIN", "BTC"],
    assetClasses: ["equities", "crypto"],
    eventType: "company-news",
    body: "Coinbase agreed to acquire an international crypto-derivatives platform for $2.9 billion in cash and stock, its largest deal to date, expanding its footprint in perpetual futures outside the US.",
    marketReaction: [
      { instrument: "COIN", move: "+4.2%" },
    ],
  },
  {
    minutesAgo: 600,
    headline: "RBA HOLDS CASH RATE AT 3.60%, FLAGS 'GRADUAL' EASING PATH AHEAD",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: [],
    assetClasses: ["forex"],
    pairs: ["AUD/USD"],
    eventType: "econ-release",
    body: "The Reserve Bank of Australia left its cash rate unchanged at 3.60% and said any further easing would be gradual and data-dependent. The Aussie firmed modestly as some traders had positioned for a cut.",
    marketReaction: [
      { instrument: "AUD/USD", move: "+0.4%" },
    ],
  },
  {
    minutesAgo: 630,
    headline: "@elonmusk: Optimus production line V3 now targeting 10k units/month by end of next year",
    source: "@elonmusk",
    sourceType: "social",
    impact: "medium",
    tickers: ["TSLA"],
    assetClasses: ["equities", "options"],
    eventType: "tweet",
    body: "Elon Musk posted overnight that Tesla's Optimus humanoid robot line is targeting a 10,000 units/month run-rate by the end of next year, a faster ramp than previously communicated on earnings calls. Shares ticked up in overnight trading on the post.",
    marketReaction: [
      { instrument: "TSLA", move: "+1.5%" },
    ],
  },
  {
    minutesAgo: 660,
    headline: "Samsung flags 56% jump in Q2 operating profit on memory recovery",
    source: "Reuters",
    sourceType: "wire",
    impact: "medium",
    tickers: ["MU", "SMH"],
    assetClasses: ["equities"],
    eventType: "earnings",
    body: "Samsung Electronics guided second-quarter operating profit up 56% year over year, ahead of estimates, on recovering memory prices and HBM shipments. Micron traded higher in sympathy overnight.",
    marketReaction: [
      { instrument: "MU", move: "+2.7%" },
    ],
  },
  {
    minutesAgo: 690,
    headline: "ORCL: CLOUD BOOKINGS BACKLOG TOPS $180B; SIGNS TWO 'GIGAWATT-SCALE' AI DEALS",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["ORCL", "NVDA"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Oracle disclosed remaining performance obligations above $180 billion after signing two gigawatt-scale AI compute contracts, according to a filing published after yesterday's close. Shares jumped in extended trading and held the gains overnight.",
    marketReaction: [
      { instrument: "ORCL", move: "+6.1%" },
      { instrument: "NQ", move: "+0.3%" },
    ],
  },
  {
    minutesAgo: 720,
    headline: "New Zealand Q2 CPI 2.9% y/y, above RBNZ midpoint; kiwi pops",
    source: "Stats NZ",
    sourceType: "econ-calendar",
    impact: "low",
    tickers: [],
    assetClasses: ["forex"],
    pairs: ["NZD/USD"],
    eventType: "econ-release",
    body: "New Zealand inflation printed 2.9% year over year, above the RBNZ's 2% target midpoint, trimming expectations for further near-term easing.",
    marketReaction: [
      { instrument: "NZD/USD", move: "+0.5%" },
    ],
  },
  {
    minutesAgo: 750,
    headline: "Chevron greenlights $6B Gulf deepwater expansion; first oil seen 2028",
    source: "Bloomberg",
    sourceType: "outlet",
    impact: "low",
    tickers: ["CVX", "XLE"],
    assetClasses: ["equities"],
    eventType: "company-news",
    body: "Chevron approved a $6 billion deepwater expansion in the Gulf, its largest domestic upstream commitment in five years, targeting first production in 2028.",
  },
  {
    minutesAgo: 780,
    headline: "SEC said to circulate draft framework for equity-market on-chain settlement pilots",
    source: "Bloomberg",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["COIN", "HOOD", "BTC"],
    assetClasses: ["equities", "crypto"],
    eventType: "company-news",
    body: "The SEC has circulated a draft framework among commissioners that would allow limited pilots of on-chain settlement for US equities, people familiar with the matter said. Crypto-adjacent brokers rose overnight on the report.",
    marketReaction: [
      { instrument: "HOOD", move: "+3.3%" },
    ],
  },
  {
    minutesAgo: 810,
    headline: "India's CPI eases to 3.1%, lowest in five years, boosting RBI cut bets",
    source: "Reuters",
    sourceType: "wire",
    impact: "low",
    tickers: ["INDA"],
    assetClasses: ["equities", "forex"],
    pairs: ["USD/INR"],
    eventType: "econ-release",
    body: "Indian consumer inflation cooled to 3.1% in June, a five-year low, strengthening the case for another Reserve Bank of India rate cut this quarter.",
  },
  {
    minutesAgo: 840,
    headline: "LLY: PHASE 3 ORAL GLP-1 MEETS PRIMARY ENDPOINT; FILING PLANNED THIS YEAR",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["LLY", "NVO"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Eli Lilly said its oral GLP-1 candidate met the primary endpoint in a Phase 3 obesity trial with average weight loss of 12.6% at 68 weeks and a discontinuation rate in line with injectables. The company plans regulatory submission this year. Novo Nordisk ADRs fell in European trading.",
    marketReaction: [
      { instrument: "LLY", move: "+5.4%" },
      { instrument: "NVO", move: "-4.0%" },
    ],
  },
  {
    minutesAgo: 870,
    headline: "Euro-zone PMIs revised up; composite back above 50 for first time in four months",
    source: "S&P Global",
    sourceType: "econ-calendar",
    impact: "low",
    tickers: [],
    assetClasses: ["forex", "futures"],
    pairs: ["EUR/USD"],
    eventType: "econ-release",
    body: "Final euro-zone composite PMI was revised up to 50.4, crossing back into expansion territory for the first time since March, led by services in Spain and Italy.",
  },
  {
    minutesAgo: 900,
    headline: "GM to idle two EV plants for retooling; cuts full-year EV output target",
    source: "Detroit Free Press",
    sourceType: "outlet",
    impact: "low",
    tickers: ["GM", "F"],
    assetClasses: ["equities"],
    eventType: "company-news",
    body: "General Motors will idle two EV assembly plants for six weeks of retooling and trimmed its full-year EV production target, citing slower-than-planned demand in entry segments.",
  },
  {
    minutesAgo: 930,
    headline: "AAPL SAID TO PLAN AI SERVER CHIP WITH BROADCOM FOR 2027 DEPLOYMENT — REPORT",
    source: "The Information",
    sourceType: "outlet",
    impact: "medium",
    tickers: ["AAPL", "AVGO"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Apple is developing its first AI server chip with Broadcom for deployment in 2027, a report said, part of an effort to reduce reliance on external cloud compute for Apple Intelligence workloads.",
    marketReaction: [
      { instrument: "AAPL", move: "+0.8%" },
      { instrument: "AVGO", move: "+1.9%" },
    ],
  },
  {
    minutesAgo: 955,
    headline: "Brazil central bank holds Selic at 14.75%, signals extended pause",
    source: "Reuters",
    sourceType: "wire",
    impact: "low",
    tickers: ["EWZ"],
    assetClasses: ["equities", "forex"],
    pairs: ["USD/BRL"],
    eventType: "econ-release",
    body: "Brazil's central bank kept the Selic rate at 14.75% and signaled it would remain at the current level for a prolonged period to ensure inflation converges to target.",
  },
];

let seq = 0;
const makeId = () => `tw-${(++seq).toString().padStart(3, "0")}`;

export const mockNewsItems: NewsItem[] = seeds.map(({ minutesAgo, ...rest }) => ({
  ...rest,
  id: makeId(),
  timestamp: ts(minutesAgo),
}));

// Pool of canned high-impact items used by simulateBreakingNews(). Each fire
// picks the next one and stamps it with the current time, so pressing the
// dev button repeatedly during a demo keeps producing fresh headlines.
type BreakingSeed = Omit<NewsItem, "id" | "timestamp">;

export const breakingPool: BreakingSeed[] = [
  {
    headline: "FED'S POWELL: 'THE TIME HAS COME FOR POLICY TO ADJUST' — UNSCHEDULED REMARKS",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: ["SPY", "QQQ", "TLT"],
    assetClasses: ["equities", "options", "futures", "forex"],
    pairs: ["EUR/USD", "USD/JPY"],
    eventType: "fed-speak",
    body: "In unscheduled remarks at an event in Washington, Fed Chair Jerome Powell said 'the time has come for policy to adjust,' the strongest signal yet that a rate cut is imminent. Equity futures spiked and short-end yields fell hard on the headline.",
    marketReaction: [
      { instrument: "ES", move: "+1.1%" },
      { instrument: "2Y", move: "-9bp" },
      { instrument: "DXY", move: "-0.6%" },
    ],
  },
  {
    headline: "NVDA HALTED — PENDING NEWS",
    source: "NYSE",
    sourceType: "wire",
    impact: "high",
    tickers: ["NVDA", "SMH", "QQQ"],
    assetClasses: ["equities", "options"],
    eventType: "company-news",
    body: "Trading in Nvidia shares was halted pending news. The halt follows unconfirmed reports of a major export-license decision. Options market makers widened quotes across the chip complex.",
    marketReaction: [
      { instrument: "NQ", move: "-0.7%" },
      { instrument: "SMH", move: "-1.8%" },
    ],
  },
  {
    headline: "US NFP +310K VS +160K EXPECTED; UNEMPLOYMENT 3.9%; AHE +0.4% M/M",
    source: "BLS",
    sourceType: "econ-calendar",
    impact: "high",
    tickers: ["SPY", "QQQ", "TLT", "GLD"],
    assetClasses: ["equities", "options", "futures", "forex"],
    pairs: ["EUR/USD", "USD/JPY"],
    eventType: "econ-release",
    body: "Nonfarm payrolls smashed expectations at +310,000 versus +160,000 consensus, with the unemployment rate falling to 3.9%. Average hourly earnings rose 0.4% on the month. Rate-cut bets were slashed on the release; yields and the dollar spiked.",
    marketReaction: [
      { instrument: "ES", move: "-0.8%" },
      { instrument: "10Y", move: "+11bp" },
      { instrument: "DXY", move: "+0.7%" },
    ],
  },
  {
    headline: "@elonmusk: Taking Tesla energy division public. Details next week.",
    source: "@elonmusk",
    sourceType: "social",
    impact: "high",
    tickers: ["TSLA"],
    assetClasses: ["equities", "options"],
    eventType: "tweet",
    body: "Elon Musk posted that Tesla plans to take its energy division public, with details promised next week. The post has not been confirmed by any company filing. Shares whipsawed as traders debated the credibility and structure of the move.",
    marketReaction: [
      { instrument: "TSLA", move: "+5.2%" },
    ],
  },
  {
    headline: "BOJ INTERVENES IN FX MARKET TO BUY YEN — MOF OFFICIAL CONFIRMS",
    source: "Reuters",
    sourceType: "wire",
    impact: "high",
    tickers: [],
    assetClasses: ["forex", "futures"],
    pairs: ["USD/JPY", "EUR/JPY"],
    eventType: "geopolitical",
    body: "Japan's Ministry of Finance confirmed yen-buying intervention after dollar-yen breached multi-decade highs. The pair dropped nearly 300 pips in minutes. Officials declined to comment on the size of the operation.",
    marketReaction: [
      { instrument: "USD/JPY", move: "-2.4%" },
      { instrument: "NKY", move: "-0.9%" },
    ],
  },
];

export function buildBreakingItem(index: number): NewsItem {
  const seed = breakingPool[index % breakingPool.length];
  return {
    ...seed,
    id: `tw-breaking-${Date.now()}`,
    timestamp: new Date().toISOString(),
  };
}
